### ISSUE TITLE
Arch AUR issues

### ISSUE THREAD

**Issue by snostormjp** [Chadsr/NordVPN-NetworkManager#107]
aur/nordnm 0.5.5-1 [installed] (13) (1.45)

I am having issues with nordapi , 

try:
        resp = requests.get(API_ADDR + '/token/verify/' + token + '/' + final_hash.hexdigest(), timeout=TIMEOUT)
        print("Printing Resp from "+API_ADDR + '/token/verify/' + token + '/' + final_hash.hexdigest())
        pp(resp.status.code)
        pp(requests.codes.ok)
        if resp.status_code == requests.codes.ok:
            print("Returning True")
            return True
        else:
            print("Returning False")
            return False
    except Exception as ex:
        print("Encounter Exception "+str(ex))
        return None

Encounter Exception 'Response' object has no attribute 'status'

resp is 401, but using the same username and password , which I printed out to screen work using a manually entered connection in NM

**Comment by Chadsr** [comment]
Hi and sorry to hear you're having issues.

This API endpoint still functions correctly for me (also through AUR), so I am not immediately sure what the problem is.

The line you have added for debugging (`pp(resp.status.code)`) is causing the exception you are currently seeing. It should read ` pp(resp.status_code)`. If you change this, it may be easier to see what the cause of the problem is.

Thanks!

**Comment by snostormjp** [comment]
Figured out my problem, sorry, my username had special characters in it specifically I had a + in my username :  user+vpn@email.com  I got nord to change my username and all is working now closing this as it is not an issue with this software but seems to be a restriction for openvpn

**Comment by Chadsr** [comment]
If this is special character related, like it seems to be, I will still check if the problem can be resolved client-side.

Thanks!
