### ISSUE TITLE
Auto connect doesn't enable auto connect in network manager?

### ISSUE THREAD

**Issue by peteruithoven** [Chadsr/NordVPN-NetworkManager#43]
After I've ran nordnm with -a (`sudo nordnm -uska nl normal tcp`) I noticed that the "Automatically connect to VPN when using this connection" isn't enabled. 
Is this a choice? Am I doing something wrong? 
![screenshot from 2017-11-27 03 24 13](https://user-images.githubusercontent.com/523210/33248001-8042c0d4-d322-11e7-9218-5885a10c9f4f.png)

I'm on elementary OS 0.4.1 Loki (Based on Ubuntu 16.04 LTS).

**Comment by Chadsr** [comment]
Hi,

This is the intended behaviour, at least for now. I was frustrated by the fact that network manager only offers the ability to auto connect to a VPN, per connection. My implementation of auto connect works on a global basis by creating a small dispatcher script within network manager. You can find said script at '/etc/NetworkManager/dispatcher.d/auto_vpn' after enabling auto connect.

It has however just occurred to me that I need to attempt to localise this script to the user if possible, since I have now made VPN connections localised by default. I will make an issue for that separately.

**Comment by peteruithoven** [comment]
Could you clarify what you mean with localise? You mean it's now applied to all users on a computer? 

> I was frustrated by the fact that network manager only offers the ability to auto connect to a VPN, per connection. My implementation of auto connect works on a global basis by creating a small dispatcher script within network manager. 

I also found that weird. Great you're trying this. But I'm afraid it doesn't work for me. After I disable "Automatically connect to VPN when using this connection" on a WiFi network and I switch to it the vpn doesn't seem to be enabled.

**Comment by Chadsr** [comment]
> Could you clarify what you mean with localise? You mean it's now applied to all users on a computer?

Since the last version, VPN connections 'should' be only available to the user that ran nordnm. The auto connect script is however still a global script and would be triggered by any user activating a network connection. So there may be some undesired effects with auto-connect on a multi-user system which I need to resolve.

Regarding auto connect not working for you, I will do some more thorough cross-platform testing and see what the results are. Most, if not all testing I have done until now has been on Arch, which does have a tendency to act very differently to other distros.

**Comment by peteruithoven** [comment]
Thanks for the clarification. 

Please let me know if I can help in any way.

**Comment by Chadsr** [comment]
A fix will be in the next release (#44).

I was using /bin/sh for some scripts (including the auto-connect script). However different distributions do different things with /bin/sh. Many symlink /bin/sh to /bin/bash. Elementary OS however seems to symlink to /bin/dash, so my script failed.

Anyway, it now just uses bash explicitly, which is should have from the beginning.

Thanks again for the help with the bug squashing!

**Comment by peteruithoven** [comment]
Nice! Looking forward to try it.

**Comment by Chadsr** [comment]
I have released version 0.0a15 containing the fix for this problem. Please report back when you get the chance to update and try the auto-connect again!

**Comment by peteruithoven** [comment]
I tried. It almost works perfectly, it definitely auto connects when switching to another network, but the first time I try to switch it only disconnects from the current network. I need to reselect the new network before it actually switches. I guess I should open a separate issue about it. It might have something to do with the kill switch?

**Comment by peteruithoven** [comment]
I opened: https://github.com/Chadsr/NordVPN-NetworkManager/issues/47

Since auto connect works, I'll close this issue.
