### ISSUE TITLE
Could not check PyPi for latest version 

### ISSUE THREAD

**Issue by nobicycle** [Chadsr/NordVPN-NetworkManager#72]
Thanks for the app. Please see the output below.

> $ sudo nordnm s -a sg normal tcp
> [ERROR] [nordnm.utils]: Could not check PyPi for latest version.
>      _   _               _ _   _ ___  ___
>     | \ | |             | | \ | ||  \/  |
>     |  \| | ___  _ __ __| |  \| || .  . |
>     | . ` |/ _ \| '__/ _` | . ` || |\/| |
>     | |\  | (_) | | | (_| | |\  || |  | |
>     \_| \_/\___/|_|  \__,_\_| \_/\_|  |_/   v0.3.3
> 
> [INFO] [nordnm.nordnm]: Checking for new connections to import...
> [INFO] [nordnm.nordnm]: Benchmarking servers...
> [INFO] [nordnm.nordnm]: Benchmarking complete. Took 1.97 seconds.
> [INFO] [nordnm.nordnm]: No active connections to remove.
> [INFO] [nordnm.nordnm]: Adding new connections...
> [INFO] [nordnm.nordnm]: No new connections added.
> [INFO] [nordnm.networkmanager]: DNS leak protection enabled.
> [ERROR] [nordnm.nordnm]: Auto-connect not activated: No active server found matching [sg, normal, tcp].
> [me@linux ~]$ sudo nordnm -v
> 0.3.3

Arch Linux

**Comment by Chadsr** [comment]
Thanks for the report.

The `Could not check PyPi for latest version.` error shouldn't have any effect on usability, but it does indicate that there may be some underlying issues with your network. It would appear that nordnm did successfully query the NordVPN API, otherwise `Checking for new connections to import...` would have failed and caused an early exit.

Do you possibly have a very strict firewall enforcement, or just an unreliable network connection?

In the next release, there will be improved benchmarking output, so you can see more information as to what may have failed (and be warned to check for firewalls in situations similar to this).

Would you also mind sharing your `$HOME/.nordnm/settings.conf`, to see if it is something there which is causing problems?

**Comment by nobicycle** [comment]
Understood. Thanks. Settings:

> [Countries]
> # simply write country codes separated by spaces e.g. country-blacklist = gb us
> country-blacklist = 
> 
> # same as above. if this is non-empty, the blacklist is ignored
> country-whitelist = sg
> 
> [Categories]
> anti-ddos = false
> dedicated-ip-servers = false
> double-vpn = false
> onion-over-vpn = false
> p2p = false
> standard-vpn-servers = true
> 
> [Protocols]
> tcp = true
> udp = false
> 
> [Benchmarking]
> ping-attempts = 5
>

**Comment by Chadsr** [comment]
The settings seem to be fine, so I would take a guess that you have something causing problems with your network. Are you able to try on a different network, to see if the problem disappears? And has nordnm worked previously, or did you run into this issue right away?

Thanks.

**Comment by Chadsr** [comment]
Since the remaining issue here is related to no connections being added, I will close this issue and refer you to #84 where other users have experienced similar problems.
