### ISSUE TITLE
DNS Servers

### ISSUE THREAD

**Issue by leedaz** [Chadsr/NordVPN-NetworkManager#76]
Not really an issue or bug, but has Nordvpn recently changed DNS Servers ? On the site, they now state them as 103.86.89.100 and 103.86.99.100... Will you be changing them in a future update ?
I have /etc/resolv.conf write protected with chattr +i /etc/resolv.conf, but nordnm still overwrites it with the original DNS servers. (I didn't think even root could write to a file protected in this way)..??
I have no knowledge of programming at all, this post is just an observation, and I am happy to be corrected if i am wrong on this.

>

**Comment by Chadsr** [comment]
Hi and thanks for making an issue of this!

I indeed noticed this yesterday too and will be pushing an update. It's unfortunate that there is no API endpoint for the DNS servers (that I know of), so they need to be static until something like that is available.

If these nameservers are seemingly changing a lot, I may integrate them into the nordnm settings for now, so that users are able to manually edit their nameserver choices, which would mitigate the problem you're having with nordnm overwriting your updated resolv.conf.

Once I have a fix implemented and ready for release I will reference this issue, so you can see the progress.

**Comment by Chadsr** [comment]
#77 contains a fix for this, along with some more useful fixes/improvements. It will be released shortly and available through all supported package managers.

Thanks!
