### ISSUE TITLE
1.1.1.1 DNS

### ISSUE THREAD

**Issue by redni** [Chadsr/NordVPN-NetworkManager#79]
Is it possible to use 1.1.1.1 DNS with integrated NordNM? 1.1.1.1 appeared yesterday (April 1, 2018) and provides quite interesting security and speed standards.

Official site: https://1.1.1.1/

**Comment by Chadsr** [comment]
Hi and thanks for the suggestion!

I agree that using custom DNS servers should be a possibility, with a small warning about leaking un-encrypted DNS requests if not done properly.
Not sure if I would like to hard-code some options such as 1.1.1.1, but I will work on providing a "custom DNS" override in the settings. If you have a suggestion for a better approach, please let me know. Otherwise I will work on including the override in the settings.

**Comment by Chadsr** [comment]
Version 0.5.0 has just been released and includes an option in the settings (nordnm update --settings) to provide custom DNS addresses. Let me know if you have any feedback to that approach (and that it works for you as intended)!

**Comment by Chadsr** [comment]
A small note for anyone wanting to use the 1.1.1.1 DNS:

The actual DNS nameserver you need to specify is `1.0.0.1`, not `1.1.1.1`. Just thought i'd clear that up in-case anyone is confused as to why it doesn't work. :)

**Comment by peteruithoven** [comment]
Thanks for adding this! Was looking forward to it.

**Comment by Chadsr** [comment]
The way DNS is handled has been completely re-hauled in v0.5.3 onwards, so I 'believe' any issues that this new feature cause should be completely gone now. 
I will therefore close this issue. If you do encounter any problems, it might be less confusing to open a new, more specific issue post. Thanks!
