### ISSUE TITLE
Increased workload when repeating auto-connect change on the command line.

### ISSUE THREAD

**Issue by BobbyBabes** [Chadsr/NordVPN-NetworkManager#81]
**EDIT:** Chips! Again I forget to thank you for the this manager. So : Thank You!

Is this normal behaviour?
Because it introduces a wait.

The first time I use `sudo nordnm -a nl normal udp` without being connected to a VPN server, it will only do a quick auto-connect enable.
On subsequent usages though, the command will first do a download of the OVPN config files, benchmarking, removal of active connections, addition of new connections.
Commands used in succession :
`sudo nordnm -a nl normal udp`
`sudo nordnm sync -uka gb normal udp`
`sudo nordnm sync -a is normal udp`
`sudo nordnm sync -a ch normal udp`
`sudo nordnm sync -a us normal udp`
`sudo nordnm sync -a us normal tcp`

Pastebin of full copy of terminal window here : [https://pastebin.com/NrgV6Rr8](https://pastebin.com/NrgV6Rr8)

**EDIT2:** When I disconnect the `nl` server by clicking the button, both connections are dropped.
And all VPN servers disappear from Plasma's Networks widget. The default "Wired connection 1" is also disconnected. No internet! When I click the Wired Connection 1 Connect button, the VPN servers reappear in Plasma's Networks widget and the connection to the `nl` VPN server is reestablished.

**Comment by Chadsr** [comment]
The difference in workload / wait time you are witnessing is due to the two ways you can use the auto-connect option.

With the first command you ran (`sudo nordnm -a nl normal udp`), nordnm is choosing the `nl normal udp` server which has already been imported. It is therefore not doing any new benchmarking, making it a very quick change.

When you run the subsequent commands (such as `sudo nordnm sync -uka gb normal udp`), the auto-connect option is being called along with sync. This is triggering a new round of benchmarking *before* enabling the auto-connect.

So in summary:
- Use `-a` **without sync** if you just want to change the auto-connecting server quickly with the existing imports.
- Use `-a` **with sync** if you want to perform benchmarking again to refresh your imported connections before activating the auto-connect.

Regarding the second issue you mention in Edit 2:
When the `-k` kill-switch argument is provided, if a VPN connection is disconnected outside of nordnm (for whatever reason) it will take down the whole interface to prevent packets from being sent outside of the VPN tunnel. I realise this is slightly aggressive behavior but for now it was the best solution to ensure the kill-switch works as intended, without involving iptables or similar solutions. If you do not wish to have this behavior, the only option for now is to not use the kill-switch feature.

Finally, regarding KDE Plasma - I have not done any testing in a KDE environment as of yet, but I will investigate if there is anything I can do to improve the UX problems you witnessed. My first assumption is that this is the default Plasma behavior when an interface is disconnected and there's not a lot I can do about it.

In summary:
Ignoring the kill-switch feature will allow you to easily change between VPN connections from the Plasma UI as normal. If you still want to use the kill-switch, you will need to use `sudo nordnm -a <country-code> <server-type> <protocol>` to switch between connections. I realise this isn't the smoothest experience, but I have not yet found an option to make it smoother, whilst not affecting the kill-switch.

Hopefully this clears things up. If you have further questions, or ideas for improvements please let me know.
