### ISSUE TITLE
How to un-randomize mac?

### ISSUE THREAD

**Issue by notmike** [Chadsr/NordVPN-NetworkManager#95]
After I initially setup for the MAC to be randomized, I cannot seem to remove/delete that setting. Even uninstalling does not undo the randomization?

**Comment by Chadsr** [comment]
Hi,

You can remove any settings that nordnm has, by using the `nordnm remove` command. So in this case, running `sudo nordnm remove --mac-settings` will remove any mac address settings if they exist.

I have made an issue (#96) to explore the usage of an uninstall script, since any settings and files should ideally be removed by the package manager as well, so thanks for that feedback!

**Comment by Chadsr** [comment]
I should also note that the CLI is due for a re-work, so hopefully in the near future these commands are somewhat more intuitive than than they are currently.

**Comment by notmike** [comment]
Awesome, appreciate it! Issue #96 sounds like the way to go =)
